name: Publish Documentation

on:
    workflow_dispatch:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write
    pages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Deploy website
              uses: withastro/action@v5
              with:
                  path: ./docs
                  node-version: 24
                  package-manager: pnpm@10

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
